spring:
  application:
    name: library
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jwt:
    access_token_validity: 10
    refresh_token_validity: 30